# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Erwan Haquet - Blog
email: erwan.haquet@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erwanhaquet.com" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/assets/images/favicon.png"
github_username: erwan-haquet

# Build settings
plugins:
    - jekyll-feed
source: .
incremental: false
highlighter: rouge
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge
remote_theme: "jeffreytse/jekyll-theme-yat"

# Copyright setting
# You can use any html code, currently below placeholders are available:
# * current year: {currentYear}
# * author: {author} (Value is the same as site.author)
# * copyright: (c) - ©
# * copyleft: (cleft)
# * sound recording copyright: (p) - ℗
#
# For example:
#   "Copyright (c) 2017-{currentYear} <a href="https://example.com">{author}</a>"
#   "Copyright © 2017-2021 Foobar"
#
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
    date_format: "%b %d, %Y"

# If you want more debug log, you can set true
# debug: false

# If you don't want transparent header, you can set false
# header_transparent: true

# If you want to change the content width, you can set to another value
content_width: "1200px"

# Google analytics - GA4
# google_analytics: [Measurement ID]
# enableDNT: "false"

# If you want to generate website sitemap, you can set true
# sitemap: false

# If you want to change site language, you can set lang option
lang: "fr"  # default lang is en

# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
#
# Custom color as below:
# theme_color: "#882250"

# You can choose a brand color
# Default brand colors as below:
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092
#
# brand_color: orangered
#
# Custom color as below:
# brand_color: "#1a8e42"

# You can custom selection style
# selection:
#   color: "#ff00ff"
#   background_color: "yellow"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
night_mode: "on/off"

# Code badge setting
# You can enable or disable the code badge and so on
# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
    - index.html
    - archives.html
#   - categories.html
#   - tags.html
#   - about.md

# Page default value
defaults:
    home:
        heading: "Erwan Haquet"
        subheading: "Développeur Backend PHP / Symfony - Itinéraire d'une reconversion"
        banner: ""

# Banner default settings
# These banner settings are for global banner default, but you can also
# config it by the front matter for one specific post
# banner:
#   video: null             # Video banner source
#   loop: true              # Video loop
#   volume: 0               # Video volume (100% is 1.0)
#   start_at: 0             # Video start time
#   image: null             # Image banner source
#   opacity: 1.0            # Banner opacity (100% is 1.0)
#   background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
#   height: "640px"         # Banner default height
#   min_height: null        # Banner minimum height
#   heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
#   subheading_style: null  # Custom subheading style (e.g. color: gold)

# Excerpt settings
excerpt:
    default_image: /assets/images/default-image.jpeg  # Default image when the image style is not none
    image_style: z          # Image layout style (It's value could be none, left, right, top, z, z-reverse)
    image_width: 38.2%      # Image default width
    image_height: 160px     # Image default height
    text_size: 600          # Words default size

# Pagination setting
# paginate: 5

# Photo previewer settings (PhotoSwipe 5)
# the options please refer to: https://photoswipe.com/options/
# photo_previewer:
#  gallery: "section.main"
#  children: "a.photo-swipe"
#  bgOpacity: 0.8
#  padding:
#    top: 20
#    bottom: 40
#    left: 100
#    right: 100
